### ISSUE TITLE
Add CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/arshadkazmi42.github.io#10]
Add CODE_OF_CONDUCT file same as this 
https://raw.githubusercontent.com/arshadkazmi42/custom-date-formatting/master/CODE_OF_CONDUCT.md

**Comment by giladtamam** [comment]
@arshadkazmi42 just to make sure, you want to copy this file to your repo? 
[https://raw.githubusercontent.com/arshadkazmi42/custom-date-formatting/master/CODE_OF_CONDUCT.md](url)

**Comment by arshadkazmi42** [comment]
Exactly 👍

**Comment by giladtamam** [comment]
thanks, I will do it

**Comment by arshadkazmi42** [comment]
Cool. Thanks for taking this up 👍
