### ISSUE TITLE
Remove duplicate credits from CREDITS.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/arshadkazmi42.github.io#9]
Remove duplicated credits from the [CREDITS](https://github.com/arshadkazmi42/arshadkazmi42.github.io/blob/develop/CREDITS.md)

**Comment by ananthshenoy** [comment]
Hi @arshadkazmi42 I have removed duplicate credits from CREDITS and created PR. Please review.

**Comment by arshadkazmi42** [comment]
@ananthshenoy Added comments to the PR. Can you do the requested changes.
